smtp_server:
    gateway: gator3021.hotor.com
    username: saqibullah@mcs.com.pk
    password: rqw!N9rwBYm
    port: 465
    tls : True
task_queue:
    celery_broker_url : redis://localhost:6379/0
    celery_result_backend : redis://localhost:6379/0
email:
    sender: saqibullah@mcs.com.pk
others:
  secret_key : XrayYankeeZulu